# Site settings
title: Linguadux
email: info@linguadux.hr
url: www.linguadux.hr

## TODO: napisati opis site-a
description: Do you want to maximize your stay in Zagreb by discovering shortcuts to all the city’s hidden gems? Immerse yourself in the local culture with the help of the insider tips? Learn more about the city’s history and gossipy historical titbits? Then don’t miss out on this engaging 2-hour walking tour around the city centre with a certified guide. To keep the tour tailored just for you, I work only with independent travellers, small groups and families. This way you get a chance to chitchat about the things that really interest you and skip the topics that bore you to tears. So what do you say? These tutoring classes are also for foreigners wanting to learn or perfect their Croatian. 
# "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# TODO: dodati tagove
keywords: "Tour guide, tour, translations, instrukcije, engleski"
skills: "Tour guide - Prijevodi - Poduka"
meta_author: Nuić Slavica

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  1B5D73  #1A334F #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2AA78A #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
# footer:
#   copyright: Dr. Henry Jekyll
#   location: Location
#   social: Around the Web
#   credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url: https://www.facebook.com/linguadux
  # - title: instagram
  #   url: https://www.instagram.com/linguadux.hr

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: 'Developed by <a href="https://www.kb3.hr">kb3</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
